# Generated by Django 5.0.6 on 2024-08-09 09:07

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()])),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()])),
                ('note_link', models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
