# Generated by Django 5.0.6 on 2024-07-23 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_demo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='project',
            name='note_link',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
