# Generated by Django 5.0.6 on 2024-07-26 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content_alter_page_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
