# Generated by Django 5.0.6 on 2024-08-01 09:17

import notes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, validators=[notes.validators.validate_slugify]),
        ),
    ]
