# Generated by Django 5.0.6 on 2024-08-01 10:28

import notes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(unique=True, validators=[notes.validators.validate_slugify]),
        ),
    ]
